### PR TITLE
Fixed bug that undefined method xxx for nil:NilClass when options given to search

### LINKED ISSUE #32: undefined method xxx for nil:NilClass when options given to search
# Description

- When using ActiveRecord data accessor or Mongoid data accessor
- and pass options to `search` and call `execute` causes undefined method error like following.
- This error can be reproduce by the steps which is explained later.

```
     NoMethodError:
       undefined method `in' for nil:NilClass
     # ./lib/nazrin/data_accessor/mongoid.rb:10:in `block in load_all'
     # ./lib/nazrin/data_accessor/mongoid.rb:6:in `each'
     # ./lib/nazrin/data_accessor/mongoid.rb:6:in `load_all'
     # ./lib/nazrin/data_accessor.rb:64:in `results'
     # ./lib/nazrin/search_client.rb:122:in `execute'
     # ./spec/nazrin/data_accessor/mongoid_spec.rb:27:in `block (4 levels) in <top (required)>'
```

The error occurs here .

https://github.com/tsuwatch/nazrin/blob/5d6969b6504f03ace89593bfc99f056c98046b66/lib/nazrin/data_accessor/active_record.rb#L8

In this code, right side `model` is not the method of `DataAccessor` but `nil`, because by executing `model = `, `model` is defined as a new local variable. So we failed to call methods.

## Environment

* ruby 2.5.3
* nazrin 2.6.1
* with rails 5.2.0 or mongoid 7.0.2

# How to reproduce 

Apply this patch and execute rspec. 

<details>
  <summary>patch</summary>

```diff
diff --git a/spec/nazrin/data_accessor/mongoid_spec.rb b/spec/nazrin/data_accessor/mongoid_spec.rb
index 9773fea..fa1b662 100644
--- a/spec/nazrin/data_accessor/mongoid_spec.rb
+++ b/spec/nazrin/data_accessor/mongoid_spec.rb
@@ -1,6 +1,6 @@
 require 'spec_helper'
 
-describe Nazrin::DataAccessor::Mongoid do
+describe 'Nazrin::DataAccessor::Mongoid' do
   let!(:user) { User.create(email: 'example@example.com', created_at: Time.now) }
 
   it { expect(User).to be_respond_to :search }
@@ -22,5 +22,9 @@ describe Nazrin::DataAccessor::Mongoid do
       it { expect(User.search.size(1).start(0).execute).to eq [user] }
       it { expect(User.search.size(1).start(0).execute.facets).to eq(response.facets) }
     end
+
+    context 'with options' do
+      it { expect(User.search({in: {email: ['example@example.com']}}).size(1).start(0).execute).to eq [user] }
+    end
   end
 end
```
</details>

### PR DESCRIPTION
**Pull request by totem3**
fixes #32 

1. fixed the left side `model` to `@model`. If we use `model` on the left side, `model` is defined as new local variable, and we cannot reference `model` instance method without `self`.

2. fixed `describe` arguments, because these constants are not loaded, and raises error since ruby 2.3.

### CODE REVIEW

**Comment by totem3** [comment]
Thank you 😄

File: lib/nazrin/data_accessor/active_record.rb [hunk 1]
```diff
@@ -5,7 +5,7 @@ class ActiveRecord < Nazrin::DataAccessor
       def load_all(ids)
         records_table = {}
         options.each do |k, v|
-          model = model.send(k, v)
+          @model = model.send(k, v)
```
Comment (AMHOL) [inline lib/nazrin/data_accessor/active_record.rb]: Sorry, bit late here, but is it an issue that this mutates the `@model` ivar? Or is a data accessor created for every request? One option for immutable `@model` is:

```ruby
relation = options.reduce(model) { |rel, (k, v)| rel.send(k, v) }

relation.where(id: ids).each do |record|
  # ...
```

File: lib/nazrin/data_accessor/mongoid.rb [hunk 2]
```diff
@@ -4,7 +4,7 @@ class Mongoid < Nazrin::DataAccessor
       def load_all(ids)
         documents_table = {}
         options.each do |k, v|
-          model = if v.nil?
+          @model = if v.nil?
```
Comment (AMHOL) [inline lib/nazrin/data_accessor/mongoid.rb]: For this one can do:

```ruby
relation = options.reduce(model) { |rel, send_args| rel.send(*send_args.compact) }

relation.where('_id' => { '$in' => ids }).each do |document|
  # ...
```

File: lib/nazrin/data_accessor/active_record.rb (hunk 1 above)
Comment (tsuwatch) [reply lib/nazrin/data_accessor/active_record.rb]: That makes sense...
That sounds great, `@model` must be immutable.
